// <auto-generated />
namespace EFDBFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddingExtraColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingExtraColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202004250800462_Adding Extra Column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
